# Generated by Django 2.1.1 on 2018-09-27 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canoneras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canonera',
            old_name='code',
            new_name='name',
        ),
    ]
