# Generated by Django 2.1.1 on 2018-09-27 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canoneras', '0002_auto_20180927_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonera',
            name='borrowed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
