# Generated by Django 2.1.1 on 2018-10-09 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canoneras', '0003_canonera_borrowed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonera',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
