# Generated by Django 2.1.1 on 2018-10-25 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('canoneras', '0004_auto_20181009_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canonera',
            name='borrowed_by',
        ),
        migrations.AddField(
            model_name='canonera',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='canonera',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
